batch_size: 64
criterion:
  name: "BCE"
  kwargs: null
optimizer:
  name: "adam"
  kwargs:
    lr: 1e-4
    weight_decay: 0.00
max_epoch: 2
patience: 50
info_freq: 5
stop_crit: "acc"
# maybe add what to log and what not?