batch_size: 64
critierion:
  name: "BCE"
  kwargs: null
optimizer:
  name: "adam"
  optimizer_kwargs:
    lr: 1e-4
    weight_decay: 0.00
max_epoch: 200
patience: 35
# maybe add what to log and what not?