name: "cricketx"
gen_dow_kwargs:
  name: "cricketx"
  size: null
  seed: 42
  noise: null
  circ_factor: null
  dow_link:
    - "https://www.cs.ucr.edu/~eamonn/time_series_data_2018/UCRArchive_2018.zip"
  dow_password: "someone"
split: [0.5, 0.25, 0.25]
split_seed: 42
use_ucr_split: true
overwrite: false
scaler: minmax
