criterion: 
  name: "negative log-likelihood"
  kwargs:
    eps: 1e-8
optimizer:
  name: "adam"
  kwargs:
    lr: 1e-4
    weight_decay: 0.00
max_epoch: 150
batch_size: 32 # samples loaded per categorisation step for all classes involved
patience: 35
auto_stack: True
auto_unbind: False
stop_crit: "acc"
watch_freq: 300
update_freq: 20