max_epoch: 20
r_real: 1.0 # ratio n_real = n_synth * r_real
d_criterion:
  name: "bce"
  kwargs: null
g_criterion: 
  name: "bce"
  kwargs: null
d_optimizer:
  name: "adam"
  kwargs:
    lr: 1e-4
    weight_decay: 0.00
g_optimizer:
  name: "adam"
  kwargs:
    lr: 1e-4
    weight_decay: 0.00
acc_drop_tol: 0.1
check_freq: 4
toViz: True
info_freq: 2
watch_freq: 1
retrain: 
  max_epoch: 40
  batch_size: 64 # samples loaded per categorisation step for all classes involved
  criterion: 
    name: "negative log-likelihood"
    kwargs:
      eps: 1e-8
  optimizer:
    name: "adam"
    kwargs:
      lr: 1e-4
      weight_decay: 0.00
  patience: 10
  stop_crit: "acc"
  update_freq: 20
  toViz: False
  watch_freq: 1000
  auto_stack: True
  auto_unbind: False
smoothing: 0.0
