num_bins: 200
n_real: 8
r_synth: 1.0 # ratio n_synth / n_real
d_criterion:
  name: "bce"
  kwargs: null
g_criterion: 
  name: "bce"
  kwargs: null
d_optimizer:
  name: "adam"
  kwargs:
    lr: 1e-4
    weight_decay: 0.00
g_optimizer:
  name: "adam"
  kwargs:
    lr: 1e-4
    weight_decay: 0.00
max_epoch: 10
retrain_crit: "loss"
stopping_crit: "acc"
acc_drop_tol: 0.01
check_freq: 1
info_freq: 1
patience: 5
smoothing: 0.0
retrain_cfg: 
  criterion: 
    name: "negative log-likelihood"
    kwargs:
      eps: 1e-8
  optimizer:
    name: "adam"
    kwargs:
      lr: 1e-4
      weight_decay: 0.00
  max_epoch: 40
  batch_size: 32 # samples loaded per categorisation step for all classes involved
  patience: 5
  auto_stack: True
  auto_unbind: False
  print_early_stop: True
  print_updates: True